# Generated by Django 6.0 on 2026-01-16 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_report_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_report_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_day_of_week',
            field=models.CharField(
                blank=True,
                choices=[
                    ('monday', 'Monday'),
                    ('tuesday', 'Tuesday'),
                    ('wednesday', 'Wednesday'),
                    ('thursday', 'Thursday'),
                    ('friday', 'Friday'),
                    ('saturday', 'Saturday'),
                    ('sunday', 'Sunday'),
                ],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_frequency',
            field=models.CharField(
                choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')],
                default='daily',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_range_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_schedule_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
    ]
